version: '3'
services:
  api:
    image: kanaheijoy/golang-dev:latest
    ports:
      - 30030:30030
    volumes:
      - ./:/go/src/github.com/joyching/golang-practice
    environment:
      - GO111MODULE=on
    tty: true
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 30040:3306
    command:
      - --innodb-buffer-pool-size=64M
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "homestead"
      MYSQL_USER: "homestead"
      MYSQL_PASSWORD: "secret"
